Moved $USAGE into its own file

diff --git a/files/awsm b/files/awsm
--- a/files/awsm
+++ b/files/awsm
@@ -5,38 +5,10 @@ set -euo pipefail
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 source $DIR/awsm-cli/_common_logging.sh
 
-USAGE=$(cat <<-EOS
-AWSM (read: awesome) Command Line Wrapper
-  An awesome wrapper for AWS CLI, written in Bash, that allows usages of *nix pipes to chain multiple AWS CLI commands together for better user experiences.
-
-Usage:
-  $ awsm <command> <subcommand> [ ... ]
-
-Examples:
-  $ awsm ec2 describe-regions --regions "us-west-2 us-east-1"
-  RegionName
-  us-east-1
-  us-west-2
-
-  $ awsm ec2 describe-regions --regions us-west-2 | awsm ec2 describe-availability-zones | column -t
-  Region     ZoneName
-  us-west-2  us-west-2a
-  us-west-2  us-west-2b
-  us-west-2  us-west-2c
-
-  $ awsm ec2 describe-regions --regions ap-south-1 | awsm ec2 describe-vpcs | awsm ec2 describe-subnets | column -t
-  Region      VpcId         AvailabilityZone  SubnetId         CidrBlock       State
-  ap-south-1  vpc-57f3123e  ap-south-1b       subnet-e52d0eaf  172.31.0.0/20   available
-  ap-south-1  vpc-57f3123e  ap-south-1a       subnet-ba6f89d3  172.31.16.0/20  available
-
-
-EOS
-)
-
 while true; do
   case "${1:-}" in
     -h | --help)
-      echo "$USAGE" >&2
+      echo "$(cat "$DIR/awsm-cli/USAGE")" >&2
       exit 1
       ;;
     --?)
@@ -75,7 +47,7 @@ elif [ "$command" == "internal" ]; then
   shift 2
   exec "$DIR/awsm-cli/${subcommand}.awk" "$@"
 else
-  [ ! -z "$command" ] && [ ! -z "$subcommand" ]      || die "$(ansi.red "ERROR"): Both \`command\` and \`subcommand\` are required. See usage.\n\n$USAGE"
+  [ ! -z "$command" ] && [ ! -z "$subcommand" ]      || die "$(ansi.red "ERROR"): Both \`command\` and \`subcommand\` are required. See usage.\n\n$(cat "$DIR/awsm-cli/USAGE")"
   [ -f "$DIR/awsm-cli/${command}-${subcommand}.sh" ] || die "$(ansi.red "ERROR"): AWSM does not yet support command \`$command\` and subcommand \`$subcommand\`."
 
   shift 2
