Use .sh file existence check to tell whether a ec2 command/subcommand is supported or not

diff --git a/files/awsm b/files/awsm
--- a/files/awsm
+++ b/files/awsm
@@ -4,32 +4,35 @@ set -euo pipefail
 
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 USAGE=$(cat <<-EOS
-  Name: AWSM (read: awesome) Command Line Wrapper
+AWSM (read: awesome) Command Line Wrapper
 
-  Description:
-    An awesome wrapper for AWS CLI, written in Bash, that allows usages of *nix pipes to chain multiple AWS CLI commands together for better user experiences.
+Usage:
+  $ awsm <command> <subcommand> [ ... ]
 
-  Examples:
-    $ awsm ec2 describe-regions --regions "us-west-2 us-east-1"
-    us-east-1
-    us-west-2
+Description:
+  An awesome wrapper for AWS CLI, written in Bash, that allows usages of *nix pipes to chain multiple AWS CLI commands together for better user experiences.
 
-    $ awsm ec2 describe-regions --regions us-west-2 | awsm ec2 describe-availability-zones
-    us-west-2       us-west-2a
-    us-west-2       us-west-2b
-    us-west-2       us-west-2c
+Examples:
+  $ awsm ec2 describe-regions --regions "us-west-2 us-east-1"
+  us-east-1
+  us-west-2
 
-    $ awsm ec2 describe-regions --regions ap-south-1 | awsm ec2 describe-vpcs | awsm ec2 describe-subnets
-    ap-south-1      vpc-57f3123e    ap-south-1b     subnet-e52d0eaf 172.31.0.0/20   available       n/a
-    ap-south-1      vpc-57f3123e    ap-south-1a     subnet-ba6f89d3 172.31.16.0/20  available       n/a
+  $ awsm ec2 describe-regions --regions us-west-2 | awsm ec2 describe-availability-zones
+  us-west-2       us-west-2a
+  us-west-2       us-west-2b
+  us-west-2       us-west-2c
+
+  $ awsm ec2 describe-regions --regions ap-south-1 | awsm ec2 describe-vpcs | awsm ec2 describe-subnets
+  ap-south-1      vpc-57f3123e    ap-south-1b     subnet-e52d0eaf 172.31.0.0/20   available       n/a
+  ap-south-1      vpc-57f3123e    ap-south-1a     subnet-ba6f89d3 172.31.16.0/20  available       n/a
 EOS
 )
 
 while getopts ":h" opt; do
   case $opt in
     h)
-      echo "$USAGE"
-      exit 0
+      echo "$USAGE" >&2
+      exit 1
       ;;
     \?)
       echo "Invalid Option: -$OPTARG" 1>&2
@@ -39,16 +42,17 @@ while getopts ":h" opt; do
 done
 shift $((OPTIND -1))
 
-command="$1"
-shift
-case "$command" in
-  autoscaling|cloudformation|ec2)
-    subcommand="$1"
-    shift
-    exec "${DIR}/awsm-cli/${command}-${subcommand}.sh" $@
-    ;;
-  \?)
-    echo "Invalid Option: -$OPTARG" 1>&2
-    exit 1
-    ;;
-esac
+command="${1:-}"
+subcommand="${2:-}"
+[ ! -z "$command" ] && [ ! -z "$subcommand" ] || {
+  printf "ERROR: Both \`command\` and \`subcommand\` are required. See usage.\n\n$USAGE\n" >&2
+  exit 1
+}
+
+[ -f "$DIR/awsm-cli/${command}-${subcommand}.sh" ] || {
+  printf "ERROR: AWSM does not yet support command \`$command\` and subcommand \`$subcommand\`.\n" >&2
+  exit 1
+}
+shift 2
+
+exec "$DIR/awsm-cli/${command}-${subcommand}.sh" $@
